### ISSUE TITLE
Apache compression causes content-length and meta to be mismatched

### ISSUE THREAD

**Issue by phil-dileo** [arista-eosplus/ztpserver#316]
When compression is enabled in Apache it will return a file that is smaller than the resulting /meta check.

Typical error message: 
ERROR: JPE15008000: Bootstrap process failed:
   executing action failed (replace_config): Unable to retrieve config from URL ("content-length" for http://x.x.x.x:8080/nodes/JPE15008000/startup-config does not match metadata: 3355 != 1328)

**Comment by petereh** [comment]
good posted i found this useful in my setup !!

**Comment by jerearista** [comment]
Evaluation: When mod_deflate is enabled on the ebserver, gzip/deflate can save bandwidth but make it unreliable to determine the uncompressed size of a file to determine if there is enough freespace available on the filesystem.  This would especially be an issue on files over 4G (not an immediate issue) due to the original file size being stored as a 32-bit value.  Removing the Accept-Encoding header from bootstrap client requests tells the server NOT to compress files in transport.  We can revisit this if this causes an issue for anyone.
